### ISSUE TITLE
Request for Feature: UNION

### ISSUE THREAD

**Issue by ondohotola** [mithrandie/csvq#2]
Hi,

the one thing I am missing in this awesome piece of code, is a UNION clause.

Can you contemplate this?

el

**Comment by mithrandie** [comment]
Set operaters like UNION, EXCEPT and INTERSECT are already implemented. Please refer to the following url.

[https://mithrandie.github.io/csvq/reference/set-operators.html](https://mithrandie.github.io/csvq/reference/set-operators.html)

That syntax should work correctly. (as long as I have not misunderstood SQL...

Thanks for watching.

**Comment by ondohotola** [comment]
Hi,

I am unable to turn the color output off, it's on by default (1.6.2)

Any advice?

el

**Comment by mithrandie** [comment]
I created the issue #3 . for this bug. Please wait to fix.
As a workaround, you can specify the option "--color=false".

Fix report for this bug will be done with issue #3 .
Thanks.
