### ISSUE TITLE
Nix package for csvq

### ISSUE THREAD

**Issue by derekmahar** [mithrandie/csvq#29]
Please make `csvq` available as a [Nix package](https://github.com/NixOS/nixpkgs).

**Comment by mithrandie** [comment]
Packaging on other platforms is pending at this time.

Related Issue: #28

**Comment by derekmahar** [comment]
There is a [csvq package](https://search.nixos.org/packages?channel=23.05&show=csvq&from=0&size=50&sort=relevance&type=packages&query=csvq) in [Nix](https://github.com/NixOS/nix).  I don't know how long it's been available, but I just encountered it today.
