### ISSUE TITLE
Color output is on by default.

### ISSUE THREAD

**Issue by mithrandie** [mithrandie/csvq#3]
This bug will appear in v1.6.2.

To avoid it, you can specify an option "--color=false".

**Comment by ondohotola** [comment]
Thank you.

To be honest I like the color as the default, and option such as
--colour=false is very helpful (when this runs under a non ansi
terminal)

I am not in any hurry, I just wanted to advise as I use this on a daily
basis :-)-O

Is there a way I can donate something to the cause?

el



On 2018-11-24 15:59 , Yuki wrote:
> This bug will appear in v1.6.2.
> 
> To avoid it, you can specify an option "--color=false".

-- 
Dr. Eberhard W. Lisse          / Obstetrician & Gynaecologist (Saar)
el@lisse.NA            / *     |   Telephone: +264 81 124 6733 (cell)
PO Box 8421                  /
Bachbrecht, Namibia     ;____/

**Comment by mithrandie** [comment]
This bug has been fixed and the fix is included in the version 1.6.3.

@ondohotola Thank you for reporting.
