### ISSUE TITLE
Select Query Error - (Where Clause) ; syntax error: unexpected token ">="

### ISSUE THREAD

**Issue by Cardosaum** [mithrandie/csvq#32]
Hello all!

I just discovered this tool and was poking around with it.
Seams like some queries were not yet implemented?

Say I have this input file:
```bash
$ cat input.txt
count,string
77766,in the
73529,for the
56800,of the
48059,on the
46528,to be
43250,to the
41130,thanks for
36993,at the
34185,i love
34015,going to
```

If I try to select only those rows with `count` greater or equal to `56800`, I get this error:

```bash
$ cat input.txt | csvq -f csv "SELECT * FROM stdin WHERE count >= 56800"
[L:1 C:33] syntax error: unexpected token ">="
```

However, if I just grab everything, I do get the rows:

```bash
$ cat input.txt | csvq -f csv "SELECT * FROM stdin"
count,string
77766,in the
73529,for the
56800,of the
48059,on the
46528,to be
43250,to the
41130,thanks for
36993,at the
34185,i love
34015,going to
```

am I doing something wrong or it's just the case that this sort of queries were not yet implemented?

**Comment by ondohotola** [comment]
Count is a reserved word, so maybe try `count` ?

el

—

**Comment by mithrandie** [comment]
As @ondohotola said, you can execute the following commands.

```
$ cat input.txt | csvq -f csv 'SELECT * FROM stdin WHERE `count` >= 56800'
$ cat input.txt | csvq -f csv –ansi-quotes 'SELECT * FROM stdin WHERE "count" >= 56800'
```

> Reserved Words https://mithrandie.github.io/csvq/reference/statement.html#reserved_words
> Grammar of identifier https://mithrandie.github.io/csvq/reference/statement.html#parsing

**Comment by Cardosaum** [comment]
Oh, I should had read the documentation more carefully.

Thanks for the quick response, and great project!
