### ISSUE TITLE
single quote and double quote

### ISSUE THREAD

**Issue by alitrack** [mithrandie/csvq#34]
### Version
```
Version 1.13.3
```

### table 

```
create table winsales(
salesid,
dateid,
sellerid,
buyerid,
qty,
qty_shipped);
```
### Insert 

```
insert into winsales values(30001, '8/2/2003', 3, 'b', 10, 10);	 
```
 got error

```
[L:1 C:49] field b does not exist
```

```sql
insert into winsales values(30001, '8/2/2003', 3, "b", 10, 10);	 
```
got 

```sql
30001,0.00199700449326011,3,b,10,10
```

```sql
insert into winsales values(30001, "8/2/2003", 3, "b", 10, 10);	 
```
got what I want.

### Select 
both are correct 

```
select "3+5"
```

```
select '3+5'
```

**Comment by mithrandie** [comment]
On my system, it seems to be working well.
<img width="850" alt="Screen Shot 2020-08-29 at 18 34 35" src="https://user-images.githubusercontent.com/27467120/91633855-8b99f100-ea26-11ea-99ec-5ea749bc897a.png">

Can you tell me about the following information?
- OS and the version.
- How to install csvq. (Whether you downloaded the binary, used a package manager, or built it yourself?)
- How to execute the query. (Whether it was executed as a command argument, in the REPL, or by loading the file with the SOURCE command)

**Comment by alitrack** [comment]
I just tested on macOS terminal, it works, 

this issue I met is  jupyter notebook, maybe is the issue of jupyter notebook, let me check it again.
