### ISSUE TITLE
Dry-run option

### ISSUE THREAD

**Issue by cpkio** [mithrandie/csvq#39]
It would be nice to have a `--dry-run` option, which would show results but no commit changes to actual file.

**Comment by ondohotola** [comment]
What is wrong with BEGIN WORK/ROLLBACK?

el

On 09/09/2020 11:53, cpkio wrote:
> It would be nice to have a |--dry-run| option, which would show
> results but no commit changes to actual file.
[...]


-- 
Dr. Eberhard W. Lisse   \         /       Obstetrician & Gynaecologist 
el@lisse.NA             / *      |  Telephone: +264 81 124 6733 (cell)
PO Box 8421 Bachbrecht  \      /  If this email is signed with GPG/PGP
10007, Namibia           ;____/ Sect 20 of Act No. 4 of 2019 may apply

**Comment by cpkio** [comment]
The interactive CLI is sluggish and unusable, so I'm using command line queries, which are committing right there and now. Would be useful to see in advance what's going to happen. Maybe I'm missing something?

**Comment by ondohotola** [comment]
Besides that nobody forces you to be rude to the developer of Open
Source software, and that nobody prevents you from contributing code to
speed up things, something like this works for me:

	 el@practice2:~/Downloads> csvq 'delete from r where rejection = 532;rollback'
	 11 records deleted on "/Users/el/Downloads/r.csv".
	 Rollback: file "/Users/el/Downloads/r.csv" is restored.

	 el@practice2:~/Downloads> csvq 'delete from r where rejection = 532;commit'
	 11 records deleted on "/Users/el/Downloads/r.csv".
	 Commit: file "/Users/el/Downloads/r.csv" is updated.

el


On 09/09/2020 12:23, cpkio wrote:
> The interactive CLI is sluggish and unusable, so I'm using command
> line queries, which are committing right there and now.  Would be
> useful to see in advance what's going to happen.  Maybe I'm missing
> something?
[...]


-- 
Dr. Eberhard W. Lisse   \         /       Obstetrician & Gynaecologist 
el@lisse.NA             / *      |  Telephone: +264 81 124 6733 (cell)
PO Box 8421 Bachbrecht  \      /  If this email is signed with GPG/PGP
10007, Namibia           ;____/ Sect 20 of Act No. 4 of 2019 may apply

**Comment by cpkio** [comment]
Sorry if this appeared to be rude, didn't mean to.  This was helpful, thanks. Closing.
