### ISSUE TITLE
Replace double by single quotes in example (bash compatibility)

### ISSUE THREAD

**Issue by kpym** [mithrandie/csvq#42]
In the `README.md` your example 
```shell
csvq "select id, name from `user.csv`"
```
do not work in `bash` because the back ticks are executed (`bash` is looking to run  `user.csv` and capture its output). 
My suggestion is to use single quotes:
```shell
csvq 'select id, name from `user.csv`'
```

**Comment by mithrandie** [comment]
You are right, single quotes are more appropriate. Thank you.
