### ISSUE TITLE
--allow-uneven-fields not working properly

### ISSUE THREAD

**Issue by pkoppstein** [mithrandie/csvq#59]
The `--allow-uneven-fields` command-line option does not allow jagged input properly, as illustrated by:
```
cat test.tsv | csvq --allow-uneven-fields -i tsv 'select * from STDIN LIMIT 5;'
panic: runtime error: slice bounds out of range [:2] with capacity 1
```

where

```
$ cat test.tsv
a	b	c
1	2
3
4
```

The last two lines are both missing two fields.

**Comment by mithrandie** [comment]
This bug has been fixed and the fix is included in the version 1.15.2. Thank you.
