### ISSUE TITLE
Build does not work

### ISSUE THREAD

**Issue by drmpjz** [mithrandie/csvq#60]
Downloaded tar - ball of latest release
csvq-1.15.2.tar.gz

Go version on openSuse 15.3:

localhost:/public/linux/tmp # go version
go version go1.15.12 linux/amd64

-> Should be ok, since 1.14 listed as requirement

localhost:/public/linux/tmp/csvq-1.15.2 # ls
BINARY_CODE_LICENSE  CHANGELOG.md  csvq_env.json  docs  .gitignore  go.mod  go.sum  help.go  init_windows.go  lib  LICENSE  main.go  Makefile  README.md  testdata  .travis.yml

-> Note: No build directory yet

localhost:/public/linux/tmp/csvq-1.15.2 # make
go build -trimpath  -o /public/linux/tmp/csvq-1.15.2/build/bin/
go build github.com/mithrandie/csvq: build output "/public/linux/tmp/csvq-1.15.2/build/bin/" already exists and is a directory
make: *** [Makefile:22: build] Error 1

-> Checked that build/bin does exist and is empty

**Comment by mithrandie** [comment]
The error occurs because the directory `build/bin/` does not exist. Run `mkdir -p build/bin` and then `make`, the build should be completed successfully. Or, if the directory has already been created by the previous run, just run `make` again and you should be fine.

The Makefile is provided to separate the build output from other go programs during development, and to create multi-platform binaries for distribution, so you can usually build with `go get` or `go install`. Even if you download a tar ball, if you run `go build` in that directory, the output binary will be the same.

**Comment by drmpjz** [comment]
:+1:  on the go build that works for me 

Running mkdir -p build/bin before calling make does help too. 

Stil the error message is the other way round really:

If i start from an empty directory and extract the tar-ball:
localhost:/public/linux/csvq # tar -xvf csvq-1.15.2.tar.gz 
csvq-1.15.2/
csvq-1.15.2/.gitignore
csvq-1.15.2/.travis.yml
csvq-1.15.2/BINARY_CODE_LICENSE
....

There is no build directory there:
localhost:/public/linux/csvq # cd csvq-1.15.2/
localhost:/public/linux/csvq/csvq-1.15.2 # ls
BINARY_CODE_LICENSE  CHANGELOG.md  csvq_env.json  docs  .gitignore  go.mod  go.sum  help.go  init_windows.go  lib  LICENSE  main.go  Makefile  README.md  testdata  .travis.yml

Running make:
localhost:/public/linux/csvq/csvq-1.15.2 # make
go build -trimpath  -o /public/linux/csvq/csvq-1.15.2/build/bin/
go build github.com/mithrandie/csvq: build output "/public/linux/csvq/csvq-1.15.2/build/bin/" already exists and is a directory

As confirmed by running go build -trimpath  -o /public/linux/csvq/csvq-1.15.2/build/bin/ outside of make in a fresh directory,the first command seems to create an empty build/bin, which the second "go build github.com/...." then complains about. (i.e. that it exists, not that it is missing)
Actually doing an rm -Rf build/bin and then running go build github.com/mithrandie/csvq will build successfully. So the Makefile setup seems to be not robust.

But my immediate problem is solved and I have a workaround. Feel free to either close or use it to track ideas to improve the Makefile.

**Comment by mithrandie** [comment]
The Makefile is not intended to be used by users for building, and commands called internally depend on the system environment, so I'll keep it as is.
