### ISSUE TITLE
Request for Feature

### ISSUE THREAD

**Issue by ondohotola** [mithrandie/csvq#61]
Would it be difficult to add another output format similar to TEXT but using Unicode drawing 
characters, ie what the parameter "-box" does for sqlite3?

It's just for aesthetics :-)-O

greetings, el

**Comment by mithrandie** [comment]
I want that feature too!
Maybe it's not so difficult to implement.

**Comment by mithrandie** [comment]
This feature has been included in version 1.16.0.

**Comment by ondohotola** [comment]
Fantastic!

el

—

**Comment by ondohotola** [comment]
Awesome,

changed all my functions and scripts to use -f BOX.

Is there a way of making this default, ie, what would one have to enter
into the .csvq_env.json file?

greetings, el

On 27/02/2022 08:38, Dr Eberhard W Lisse wrote:
> Fantastic!
> 
> el
> 
> —
> Sent from Dr Lisse’s iPhone/iPad
> On 26. Feb 2022, 21:47 +0200, Yuki ***@***.***>, wrote:
>>
>> Closed #61 <https://github.com/mithrandie/csvq/issues/61>.
[...]


-- 
Dr. Eberhard W. Lisse   \         /       Obstetrician & Gynaecologist
***@***.***             / *      |  Telephone: +264 81 124 6733 (cell)
PO Box 8421 Bachbrecht  \      /  If this email is signed with GPG/PGP
10007, Namibia           ;____/ Sect 20 of Act No. 4 of 2019 may apply

**Comment by mithrandie** [comment]
`.csvq_env.json` can only set a few options.
You can write statements in a specific file and run it before each execution.

```
touch $HOME/.csvqrc
echo 'SET @@FORMAT TO BOX' > $HOME/.csvqrc
```

These files will be loaded and run before each execution.

1. $XDG_CONFIG_HOME/csvq/csvqrc or $HOME/.config/csvq/csvqrc
2. $HOME/.csvqrc
3. $HOME/.csvq/csvqrc
4. CURRENT_DIRECTORY/csvqrc

cf. https://mithrandie.github.io/csvq/reference/command.html#configurations

**Comment by ondohotola** [comment]
Perfect!

Thank you

el

On 01/03/2022 13:35, Yuki wrote:
> |touch $HOME/.csvqrc echo 'SET @@FORMAT TO BOX' > $HOME/.csvqrc|

-- 
Dr. Eberhard W. Lisse   \         /       Obstetrician & Gynaecologist
***@***.***             / *      |  Telephone: +264 81 124 6733 (cell)
PO Box 8421 Bachbrecht  \      /  If this email is signed with GPG/PGP
10007, Namibia           ;____/ Sect 20 of Act No. 4 of 2019 may apply
