### ISSUE TITLE
Request for Feature / Question

### ISSUE THREAD

**Issue by ondohotola** [mithrandie/csvq#63]
Is it possible to have the (interactive) prompt in color?

Currently CSVQ:/Users/user> is not visibly different from ~/Users/user but if one could put the CSVQ of the prompt into a (bold) color it would be helpful in my view.

greetings, el

**Comment by mithrandie** [comment]
The prompt can be changed by editing the csvq configuration file.

As an example, you can save the [csvq_env.json](https://github.com/mithrandie/csvq/blob/master/csvq_env.json) file as `.csvq_env.json` in your home directory, and change the `interactive_shell.prompt` item in the file as you wish. If the `--color` option is enabled, the displayed characters will be colored according to ANSI escape sequences in the value of the `interactive_shell.prompt` item.

There are some other paths you can choose to save the configuration file besides the home directory.
[https://mithrandie.github.io/csvq/reference/command.html#configurations](https://mithrandie.github.io/csvq/reference/command.html#configurations)
