### ISSUE TITLE
Support `table_name.*`

### ISSUE THREAD

**Issue by spenserblack** [mithrandie/csvq#68]
With the following query
```
SELECT my_table.*
FROM `file.csv` my_table
```

I expected all fields from `my_table` to be selected. Instead the result is `syntax error: unexpected token "*"`.
Using `table_name.*` can be helpful to select all fields from one table, but not all fields from *all tables*.
Version: `1.15.2`

**Comment by mithrandie** [comment]
This feature has been included in version 1.17.0.
