### ISSUE TITLE
go version go1.12.1 darwin/amd64

### ISSUE THREAD

**Issue by santacruz123** [mithrandie/csvq#7]
`# github.com/mithrandie/csvq/lib/query
go/src/github.com/mithrandie/csvq/lib/query/encode.go:77:9: assignment mismatch: 2 variables but csv.NewWriter returns 1 values
go/src/github.com/mithrandie/csvq/lib/query/encode.go:149:10: assignment mismatch: 2 variables but fixedlen.NewWriter returns 1 values
go/src/github.com/mithrandie/csvq/lib/query/encode.go:166:10: assignment mismatch: 2 variables but fixedlen.NewWriter returns 1 values`

**Comment by mithrandie** [comment]
@santacruz123 

The version of dependency package "github.com/mithrandie/go-text" may not match.
Could you get the latest version of "github.com/mithrandie/go-text" and try rebuilding?

If you are using Go 1.11 or later, I recommend to use the go module feature.
```
$ cd GOPATH/src/github.com/mithrandie/csvq
$ env GO111MODULE=on go install
```
