### ISSUE TITLE
feature : set the default format to csv when the output is piped

### ISSUE THREAD

**Issue by kpym** [mithrandie/csvq#71]
The text output format is not very useful when we use it as input to another program. Perhaps you can change the default format to `csv` if stdout is sent to another program. This can be done like in this [SX answer](https://stackoverflow.com/a/43947435) but with `os.Stdout` instead of `os.Stdin`, I think.

**Comment by ondohotola** [comment]
In the meantime you can use '--format CSV'

el

**Comment by kpym** [comment]
@ondohotola I know that I can do this. Thanks.

**Comment by ktzanev** [comment]
Thanks for considering this request.
I don't agree with your logic.  The terminal output is supposed to be human readable. The pipe output is supposed to be machine readable. For example all good tools that have colorful terminal output produce raw (without colors) output when they are piped.
I agree that the data should be the same, but the form should be adapted to humans or to machines.
In any case it is your choice and I appreciate that you took the time to consider my request. 🙏

**Comment by mithrandie** [comment]
That makes sense. You may be right.
I will add this fix to the next release. Thank you for explaining.

**Comment by mithrandie** [comment]
This feature has been included in version 1.17.3.

**Comment by kpym** [comment]
Fantastic ! Thank you for the quality of your work and your responsiveness 🙏
