### ISSUE TITLE
Package for Raspbian GNU/Linux 10 (buster) ?

### ISSUE THREAD

**Issue by ondohotola** [mithrandie/csvq#72]
Hi,

Is there a package/PPA for Raspbian GNU/Linux 10 (buster)? 

If not, can you please add this?

https://github.com/mithrandie/csvq/releases/download/v1.16.0/csvq-v1.16.0-linux-arm.tar.gz works on the PI.

greetings, el

**Comment by derekmahar** [comment]
This would also be useful for Ubuntu Server for Raspberry Pi 4.  I guess you would just have to add the ARM64 binary to the PPA.

**Comment by mithrandie** [comment]
I haven't tested it, but I've added arm64 packages to Ubuntu PPA.

https://launchpad.net/~mithrandie/+archive/ubuntu/csvq/+packages

**Comment by derekmahar** [comment]
It works.  I just installed csvq in Ubuntu Server on one of my Raspberry Pi 4 servers.

**Comment by ondohotola** [comment]
add-apt-repository gives an error on my PI, what have you (put) in
/etc/apt/sources.list?

greetings, el

On 02/03/2022 10:44, Derek Mahar wrote:
> It works.  I just installed csvq in Ubuntu Server on one of my
> Raspberry Pi 4 servers.
[...]
> 
-- 
Dr. Eberhard W. Lisse   \         /       Obstetrician & Gynaecologist
***@***.***             / *      |  Telephone: +264 81 124 6733 (cell)
PO Box 8421 Bachbrecht  \      /  If this email is signed with GPG/PGP
10007, Namibia           ;____/ Sect 20 of Act No. 4 of 2019 may apply
