### ISSUE TITLE
feature request : CREATE TABLE IF NOT EXISTS

### ISSUE THREAD

**Issue by kpym** [mithrandie/csvq#77]
I wanted to replace sqlite with csvq in a tool where sqlite is overkill and it is better to keep pure go.
This tool used `CREATE TABLE IF NOT EXISTS`. I know I can check for the existence of the file before calling ``CREATE TABLE`` but it will be easier if we stick to SQL and besides `CREATE TABLE IF NOT EXISTS` can also send an error if the existing file has a different format than the requested one.

**Comment by mithrandie** [comment]
This feature has been included in version 1.17.4.

**Comment by kpym** [comment]
Thanks @mithrandie 🙏 
I am impressed by your responsiveness.
