### ISSUE TITLE
panic: runtime error: index out of range [375] with length 0

### ISSUE THREAD

**Issue by aaronmlee** [mithrandie/csvq#79]
steps:
1. create a table 
`csvq 'CREATE TABLE IF NOT EXISTS common_record (day, sleep_hrs_x, sleep_hrs_y, sleep_hrs_z);'`
2. Try to select into table from an existing CSV 
`csvq 'REPLACE INTO common_record (day, sleep_hrs_x) USING (day) select day, total_sleep_duration from x_sleep'`

note, `day` is a string date field. 

results: 

panic: runtime error: index out of range [375] with length 0

goroutine 67 [running]:
github.com/mithrandie/csvq/lib/query.(*View).replace.func2(0x177)
	github.com/mithrandie/csvq/lib/query/view.go:2231 +0x1a0
github.com/mithrandie/csvq/lib/query.(*GoroutineTaskManager).run(0x140001f1880, {0x10338d618, 0x140001f1740}, 0x14000ecac00, 0x0?)
	github.com/mithrandie/csvq/lib/query/goroutine_manager.go:156 +0xfc
created by github.com/mithrandie/csvq/lib/query.(*GoroutineTaskManager).Run
	github.com/mithrandie/csvq/lib/query/goroutine_manager.go:171 +0xbc
panic: runtime error: index out of range [750] with length 0

goroutine 68 [running]:
github.com/mithrandie/csvq/lib/query.(*View).replace.func2(0x2ee)
	github.com/mithrandie/csvq/lib/query/view.go:2231 +0x1a0
github.com/mithrandie/csvq/lib/query.(*GoroutineTaskManager).run(0x140001f1880, {0x10338d618, 0x140001f1740}, 0x14000ecac00, 0x0?)
	github.com/mithrandie/csvq/lib/query/goroutine_manager.go:156 +0xfc
created by github.com/mithrandie/csvq/lib/query.(*GoroutineTaskManager).Run
	github.com/mithrandie/csvq/lib/query/goroutine_manager.go:171 +0xbc

found on Monterey 12.4 M1

**Comment by mithrandie** [comment]
This bug has been fixed in Release v1.17.6.
