### ISSUE TITLE
sort the options

### ISSUE THREAD

**Issue by ondohotola** [mithrandie/csvq#80]
I would find it very helpful if

`csvq --help`

were to return the Options sorted alphabetically.

el

**Comment by mithrandie** [comment]
If the options were to be sorted, do you think it would be more appropriate to sort by long-name or short-name?

**Comment by ondohotola** [comment]
Long.

The options I use regularly I know by heart (short versions) but when I look for something rarely used I look for the long ones as they are informative (even if I then use the short one).

I assume that’s the way for others too.

Is there any way to support this project? I use csvq in several workflows in my practice and a little company I run on a daily basis and can not imagine doing without it any more.

You may contact me directly off list, but another little (LaTeX related) project has “wish list” on Amazon for hardware, another has a PayPal account, things of that nature.

greetings, el


--
Dr. Eberhard W. Lisse \ / Obstetrician & Gynaecologist
***@***.*** / * | Telephone: +264 81 124 6733 (cell)
PO Box 8421 Bachbrecht \ / If this email is signed with GPG/PGP
10007, Namibia ;____/ Sect 20 of Act No. 4 of 2019 may apply

**Comment by mithrandie** [comment]
OK, I'll fix it later.

This project does not require financial support for now.

**Comment by mithrandie** [comment]
This fix is included in version 1.17.9 and later.


I added features without much thought, so the option names are not consistent, and it may be difficult to find them after all.
I want to change the option names someday...
