### ISSUE TITLE
top support

### ISSUE THREAD

**Issue by peheje** [mithrandie/csvq#9]
Is the top command supported in any way?

E.g. `select top 10 * from myfile`

**Comment by mithrandie** [comment]
You can use limit clause or fetch clause in select query.

[https://mithrandie.github.io/csvq/reference/select-query.html#limit_clause](https://mithrandie.github.io/csvq/reference/select-query.html#limit_clause)

For example, the following queries will return the results you want.

```sql
SELECT * FROM filename LIMIT 10;
SELECT * FROM filename FETCH FIRST 10 ROWS ONLY;
```

**Comment by peheje** [comment]
Thanks!
